[run]
build = "npm run build"

[integrations.supabase]
slug = "supabase"
input_prompt = ""
title = ""
description = ""
resources = []
context_prompt = ""

[integrations.supabase.parameters]
project_url = "aasdf"
api_key = "sadfas"

[gptengineer-app]
project_id = "ee125e54-0854-4328-af4e-6bc2a9e710b1"
