[run]
build = "npm run build"

[integrations.supabase]
slug = "supabase"
input_prompt = ""
title = ""
description = ""
resources = []
context_prompt = ""

[integrations.supabase.parameters]
project_url = "aasdf"
api_key = "sadfas"
SUPABASE_PROJECT_URL = "https://nvfxbesbgohafwkbhsvv.supabase.co"
nSUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZnhiZXNiZ29oYWZ3a2Joc3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUxNTcwMjcsImV4cCI6MjAzMDczMzAyN30.2VLc7SxL3hYJ_lpO4YnMrvGKViKUIBKdooZLyZ4NL5Q"
SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZnhiZXNiZ29oYWZ3a2Joc3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUxNTcwMjcsImV4cCI6MjAzMDczMzAyN30.2VLc7SxL3hYJ_lpO4YnMrvGKViKUIBKdooZLyZ4NL5Q"

[gptengineer-app]
project_id = "ee125e54-0854-4328-af4e-6bc2a9e710b1"
