[run]
build = "npm run build"

[integrations]
[integrations.supabase]
slug = "removed"
input_prompt = ""
title = "Removed"
description = "This integration has been removed."
resources = []
context_prompt = ""

[integrations.removed]
slug = "removed"
input_prompt = ""
title = "Removed"
description = "This integration has been removed."
resources = []
context_prompt = ""

[gptengineer-app]
project_id = "ee125e54-0854-4328-af4e-6bc2a9e710b1"
